### ISSUE TITLE
Patch does not apply

### ISSUE THREAD

**Issue by Mcbeer** [transitive-bullshit/ffmpeg-gl-transition#12]
Running the command (On OSX) "git apply ~/ffmpeg-gl-transition/ffmpeg.diff" returns this error:

`Checking patch libavfilter/Makefile...
Hunk #1 succeeded at 367 (offset 15 lines).
Checking patch libavfilter/allfilters.c...
error: while searching for:
    REGISTER_FILTER(ZMQ,            zmq,            vf);
    REGISTER_FILTER(ZOOMPAN,        zoompan,        vf);
    REGISTER_FILTER(ZSCALE,         zscale,         vf);
    REGISTER_FILTER(ALLRGB,         allrgb,         vsrc);
    REGISTER_FILTER(ALLYUV,         allyuv,         vsrc);
error: patch failed: libavfilter/allfilters.c:360
error: libavfilter/allfilters.c: patch does not apply`
*Edited: Verbose version attached.

Is anything up with this plugin and the newst ffmpeg, making this not work anymore?

When trying to build after the command has failed, the follow message appears in the config.log file in ffmpeg.

`WARNING: Option --enable-filter=gltransition did not match anything`

**Comment by transitive-bullshit** [comment]
I'm guessing something changed within the ffmpeg filters list. Looking into it now.

**Comment by transitive-bullshit** [comment]
@Mcbeer this should be fixed now. ffmpeg changed the way they initialize filters in their Makefile.

Please let me know if this resolves your issue.

**Comment by Mcbeer** [comment]
@transitive-bullshit Thanks for the quick update! I added the filter manually and it worked, but looking at the new file, i should work, will test once i set up a new instance.

**Comment by Trway** [comment]
> 

can you tell me how fix this bug thanks
