### ISSUE TITLE
FFmpeg build not successfully

### ISSUE THREAD

**Issue by crdesai25** [transitive-bullshit/ffmpeg-gl-transition#14]
try to build ffmpeg with gt-transition buy got following error.
`Undefined symbols for architecture x86_64:
  "_glfwCreateWindow", referenced from:
      _setup_gl in libavfilter.a(vf_gltransition.o)
  "_glfwDestroyWindow", referenced from:
      _uninit in libavfilter.a(vf_gltransition.o)
  "_glfwInit", referenced from:
      _init in libavfilter.a(vf_gltransition.o)
  "_glfwMakeContextCurrent", referenced from:
      _setup_gl in libavfilter.a(vf_gltransition.o)
      _blend_frame in libavfilter.a(vf_gltransition.o)
  "_glfwWindowHint", referenced from:
      _setup_gl in libavfilter.a(vf_gltransition.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffmpeg_g] Error 1`

want to make a build for mac OS and android. 
Is there any better way to make a build or get inbuild gl-transition ffmpeg?

**Comment by transitive-bullshit** [comment]
The error looks like `glfw` isn't being found. Make sure it's installed properly.

Mac OS should build fine as it's been thoroughly tested. Not sure about Android.

**Comment by turengege** [comment]
@crdesai25 
This commit  may help about Android.  #16

**Comment by NCPatrick** [comment]
I'm having a similar issue in 'make' on High Sierra 10.13.5:
Undefined symbols for architecture x86_64:
  "_glfwCreateWindow", referenced from:
      _setup_gl in libavfilter.a(vf_gltransition.o)
  "_glfwDestroyWindow", referenced from:
      _uninit in libavfilter.a(vf_gltransition.o)
  "_glfwInit", referenced from:
      _init in libavfilter.a(vf_gltransition.o)
  "_glfwMakeContextCurrent", referenced from:
      _setup_gl in libavfilter.a(vf_gltransition.o)
      _blend_frame in libavfilter.a(vf_gltransition.o)
  "_glfwWindowHint", referenced from:
      _setup_gl in libavfilter.a(vf_gltransition.o)
ld: symbol(s) not found for architecture x86_64

I know glfw is installed correctly.
==> Reinstalling glfw 
==> Downloading https://homebrew.bintray.com/bottles/glfw-3.2.1.high_sierra.bottle.tar.gz
Already downloaded: /Users/patrickbrown/Library/Caches/Homebrew/glfw-3.2.1.high_sierra.bottle.tar.gz
==> Pouring glfw-3.2.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/glfw/3.2.1: 14 files, 286.3KB

I've tried multiple times. I know something is missing.

**Comment by turengege** [comment]
@NCPatrick 
hi 
please use `--extra-libs='-lGLEW -lglfw'.` when ./configure. 
edit the configure file at that line just affect the output of ./configure --help

**Comment by divysoni3** [comment]
@crdesai25 @NCPatrick have u got the solution?
