### ISSUE TITLE
Hi guys, I need some video transitions effects to use in my Android app

### ISSUE THREAD

**Issue by javidansalarian** [transitive-bullshit/ffmpeg-gl-transition#18]
Could you tell me how can I compile FFmpeg with ffmpeg-gl-transition ? Has anybody done something like this before? 

Thanks.

**Comment by transitive-bullshit** [comment]
@yongfengnice was trying to do this awhile back.

It's definitely possible, but I don't have specific instructions.  Make sure you can compile a base version of ffmpeg **first** before adding in the ffmpeg-gl-transition diff.
