### ISSUE TITLE
Porting to emscripten 

### ISSUE THREAD

**Issue by arinkverma** [transitive-bullshit/ffmpeg-gl-transition#22]
Hello Guys

Need a quick help here.

I have build this to be used in js environment.
```
emcc build/ffmpeg/ffmpeg.bc build/lame/dist/lib/libmp3lame.so build/x264/dist/lib/libx264.so \
	--post-js build/post-sync.js \
	--closure 1 -s USE_GLFW=3 -s TOTAL_MEMORY=67108864 -s OUTLINING_LIMIT=20000 -O3 --memory-init-file 0 --pre-js build/pre.js -o ffmpeg-mp4.js
```
But on runtime I am getting error as
```glReadPixels: format and type incompatible with the current read framebuffer```

How can I debug it?

**Comment by transitive-bullshit** [comment]
Hmmm, I honestly have no idea.

If you want an easier JS solution, check out [ffmpeg-concat](https://github.com/transitive-bullshit/ffmpeg-concat).

Maybe someone else here can help you with the emscripten issue.

**Comment by arinkverma** [comment]
@transitive-bullshit Thanks for quick response.
