### ISSUE TITLE
[bug] vertical coordinate is inverted from gl-transition expectations

### ISSUE THREAD

**Issue by drlukacs** [transitive-bullshit/ffmpeg-gl-transition#3]
The vertical (y) coordinate appears to be inverted: For example, the  heart.glsl transition draws an upside-down heart.

**Comment by transitive-bullshit** [comment]
Thanks for the bug report!

It looks like the ffmpeg `AVFrame` has a flipped vertical axis, so I just added a [commit](https://github.com/transitive-bullshit/ffmpeg-gl-transition/commit/e2db854ab85e092de3f5f558c6e00e5bd72d243b) to flip the `uv` that the gl-transition gets while double-flipping the `uv.y` for texture access.

I tested it locally on `heart.glsl` and it appears to work as intended.  Please let me know if this fixes your use case.

**Comment by drlukacs** [comment]
Thank you @transitive-bullshit. Problem is solved.
