### ISSUE TITLE
No such filter: 'gltransition'

### ISSUE THREAD

**Issue by Eric-HeShiPing** [transitive-bullshit/ffmpeg-gl-transition#59]
Hello, excuse me, please

In linux system，I installed the dependencies for FFMPEG build(GLFW,GLEW) And installed Xvfb and mesa

 sudo yum install mesa-libGL
 sudo yum install xorg-x11-server-Xvfb.x86_64  

My configured command is:

![image](https://user-images.githubusercontent.com/75157930/110786921-b2739280-82a7-11eb-8536-a714afe45720.png)

After executing this command in Enabled Filter log GLTransition filter is there. Then I checked for GLTransition filter using command:

./ffmpeg -v 0 -filters | grep gltransition but it shows nothing.

Then also cross checked using ffmpeg command below:

./ffmpeg -i media/0.mp4 -i media/1.mp4 -filter_complex gltransition -y out.mp4

but it shows error like,

        No such filter: 'gltransition'
	Error initializing complex filters.
	Invalid argument.

![image](https://user-images.githubusercontent.com/75157930/110787285-1f872800-82a8-11eb-9797-e316817c043f.png)

![image](https://user-images.githubusercontent.com/75157930/110787341-2dd54400-82a8-11eb-88cf-fd338114412b.png)

Am I missed something?

**Comment by Eric-HeShiPing** [comment]
solved

**Comment by alanMachineLeraning** [comment]
> solved

how to solve?

**Comment by tringuyen98** [comment]
how to solve bro

> solved

how man, can u give me a solution, thanks
