### ISSUE TITLE
ques for transition

### ISSUE THREAD

**Issue by willyangyang** [transitive-bullshit/ffmpeg-gl-transition#6]
I make the ffmpeg successfully,but I meet the problems "Error initializing filter 'gltransition' Error initializing complex filters. Operation not permitted" when I call the command“./ffmpeg -i media/0.mp4 -i media/1.mp4 -filter_complex gltransition -y out.mp4”.
Then I install the xvfb,export DISPLAY=localhost:1.0,another error occurs when the code call glCreateShader:"X Error of failed request:  BadRequest (invalid request code or no such operation)".
I have little experience with OpenGL issues over **remote connections**.My glxinfo is:
display: localhost:1  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
server glx vendor string: SGI
server glx version string: 1.4
OpenGL vendor string: Mesa Project
OpenGL renderer string: Software Rasterizer
OpenGL version string: 1.4 (2.1 Mesa 7.11)
Can you give me some help?Thank you!

**Comment by transitive-bullshit** [comment]
It definitely seems that OpenGL is not initializing properly.

How are you running `xvfb`?  Try the following (from this [tutorial](http://elementalselenium.com/tips/38-headless)):

```
Xvfb :99 &
export DISPLAY=:99
```

This thread may also be useful:  https://github.com/transitive-bullshit/ffmpeg-gl-transition/issues/5

**Comment by willyangyang** [comment]
when I print "Xvfb :99 &",I got "expected keysym, got XF86TouchpadOn: line 120 of inet
expected keysym, got XF86TouchpadOff: line 121 of inet".Next "export DISPLAY=:99",everything seems fine.However,I got the same error:"X Error of failed request: BadRequest (invalid request code or no such operation)".I debug the code and find the glCreateShader crashing.
I suspect the reason is because I remotely login server.My glxinfo is:
name of display: :99.0
display: :99  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
GLX version: 1.4
GLX extensions:
OpenGL vendor string: Mesa Project
OpenGL renderer string: Software Rasterizer
OpenGL version string: 1.4 (2.1 Mesa 7.11)
OpenGL extensions:

Is the version mismatch caused by the error?

**Comment by transitive-bullshit** [comment]
I'm really not sure the details of your setup, but if `xvfb` is throwing an error, then any opengl code won't work.  I would suggest asking your question on Stackoverflow or Superuser, as it is likely unrelated to this library itself.
