### ISSUE TITLE
ffmpeg compilation error

### ISSUE THREAD

**Issue by RoncoCo** [transitive-bullshit/ffmpeg-gl-transition#8]
Hi,

Following your instructions on how to build ffmpeg I have encountered an error while running the ./configure command I am getting the following error.

> ./configure --enable-libx264 --enable-gpl --enable-opengl --enable-filter=gltransition --extra-libs='-
> 
> lGLEW -lglfw'
> gcc is unable to create an executable file.
> If gcc is a cross-compiler, use the --enable-cross-compile option.
> Only do this if you know what cross compiling means.
> C compiler test failed.
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.

I am running the build from Windows os, my c compiler is configured and present on PATH, I am able to run ./configure successfully without the parameters.

**Comment by transitive-bullshit** [comment]
hmm, your `libs=` command seems to contain some newlines.  i'd try it making sure the output prints out corrects, without any newlines

**Comment by transitive-bullshit** [comment]
Otherwise, maybe double-check the windows ffmpeg compilation [instructions](https://trac.ffmpeg.org/wiki/CompilationGuide).  It seems like gcc isn't being invoked properly, so make sure you follow the official ffmpeg guide to compiling for your platform before trying to compile this slightly modified version.

**Comment by RoncoCo** [comment]
I have looked into the ffmpeg compilation instructions and when I try to run them the compilation is successful, Also typed the entire params for the configure but I still get the same error,

Could it be that I am missing something that need to be present in the environment variables? or any other configuration issue?

**Comment by transitive-bullshit** [comment]
I'm really not sure, as I don't have a Windows machine to test with.

Are you sure that `./configure` and `make` both build successfully for you with a vanilla checkout of ffmpeg?

You might also want to try searching for your [error](https://www.google.com/search?q=gcc+is+unable+to+create+an+executable+file.&oq=gcc+is+unable+to+create+an+executable+file.&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8).

**Comment by sutra** [comment]
If you're using Ubuntu 17.10 or something like this,
try to check if you have already installed `libglew-dev` and `libglfw3-dev`, 
or run `apt install libglew-dev libglfw3-dev` directly,
before `./configure ...`.

**Comment by ayayy** [comment]
try to use --extra-libs='-lGLEW -lEGL' instead of --extra-libs='-lGLEW -lglfw' when compiling with configure and make
