### ISSUE TITLE
C compiler test failed

### ISSUE THREAD

**Issue by anuj9196** [transitive-bullshit/ffmpeg-gl-transition#9]
I have installed FFmpeg in Ubuntu system by building from source and the version installed is 
```
ffmpeg version 3.2.2-2~16.04.york0 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.1 (Ubuntu 5.4.1-4ubuntu1~16.04.york1) 20161202
```

I tried installing this library from the beginning as given in the instruction by cloning FFmpeg from git and all.

While running
```
./configure --enable-libx264 --enable-gpl --enable-opengl \
            --enable-filter=gltransition --extra-libs='-lGLEW -lglfw'
```

I'm getting the error as **C compiler test failed**
```
gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```

How to solve this problem?

**Comment by transitive-bullshit** [comment]
Try building the base ffmpeg clone without adding `ffmpeg-gl-transition`.

This is likely unrelated to this project, and is caused by a problem in your environment's setup or dependencies.

See this [guide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) for more details.

**Comment by anuj9196** [comment]
Since I have already built the ffmpeg from source. Do I need to build it again? Will not it work with previously built version?

**Comment by transitive-bullshit** [comment]
You need to build from source with the ffmpeg-gl-transition additions applied, so yes you'll need to build again.

The snippet you pasted shows errors for both of those commands.  I would advise that you start from scratch and follow the directions explicitly.  You should be cloning ffmpeg source, applying the ffmpeg-gl-transition patch, then running configure and make on the modified source.  It looks like you're trying to apply the diff to the compiled version which will not work.

**Comment by gjmulder** [comment]
> While running
> 
> ```
> ./configure --enable-libx264 --enable-gpl --enable-opengl \
>             --enable-filter=gltransition --extra-libs='-lGLEW -lglfw'
> ```
> 
> I'm getting the error as **C compiler test failed**
> 
> ```
> gcc is unable to create an executable file.
> If gcc is a cross-compiler, use the --enable-cross-compile option.
> Only do this if you know what cross compiling means.
> C compiler test failed.
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> ```
> 
> How to solve this problem?

I solved it by:
